/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package filemanagementsystem.UI;

import filemanagementsystem.RecentsUploads;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author kalilinux
 */
public class UseableFrame extends javax.swing.JFrame {

    /**
     * Creates new form UseableFrame
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public UseableFrame() throws ClassNotFoundException, SQLException {
        initComponents();
       
       
    }
    public void photoFrame() throws ClassNotFoundException, SQLException{
        ImageIcon icon = new ImageIcon(RecentsUploads.fetchRecents1());
        Image img = icon.getImage();
        Image scaleImage = img.getScaledInstance(useLabel.getWidth(), useLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(scaleImage);
        useLabel.setIcon(image);
    }
    public void photoFrame1() throws ClassNotFoundException, SQLException{
        ImageIcon icon = new ImageIcon(RecentsUploads.fetchRecents2());
        Image img = icon.getImage();
        Image scaleImage = img.getScaledInstance(useLabel.getWidth(), useLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(scaleImage);
        useLabel.setIcon(image);
    }
   public void photoFrame2() throws ClassNotFoundException, SQLException{
      ImageIcon icon = new ImageIcon(RecentsUploads.fetchRecents3());
        Image img = icon.getImage();
        Image scaleImage = img.getScaledInstance(useLabel.getWidth(), useLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(scaleImage);
        useLabel.setIcon(image);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usePanel = new javax.swing.JPanel();
        useLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        useLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        useLabel.setOpaque(true);

        javax.swing.GroupLayout usePanelLayout = new javax.swing.GroupLayout(usePanel);
        usePanel.setLayout(usePanelLayout);
        usePanelLayout.setHorizontalGroup(
            usePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(useLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );
        usePanelLayout.setVerticalGroup(
            usePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(useLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UseableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UseableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UseableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UseableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new UseableFrame().setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(UseableFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel useLabel;
    public static javax.swing.JPanel usePanel;
    // End of variables declaration//GEN-END:variables
}
